// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    /*if (kIsWeb) {
      return web;
    }*/
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
     /*case TargetPlatform.iOS:
        return ios;*/
    /*case TargetPlatform.macOS:
        return macos;*/
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /*static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7wZb2tO1-Fs6GbDADUSTs2Qs3w08Hovw',
    appId: '1:406099696497:web:87e25e51afe982cd3574d0',
    messagingSenderId: '406099696497',
    projectId: 'flutterfire-e2e-tests',
    authDomain: 'flutterfire-e2e-tests.firebaseapp.com',
    databaseURL:
    'https://flutterfire-e2e-tests-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfire-e2e-tests.appspot.com',
    measurementId: 'G-JN95N1JV2E',
  );*/

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdF6n1r5UEgtJ2b_Ai7fRSNkgFzxJmpDs',
    appId: '1:1:965932386436:android:0d748e7cf37fd20ba9dad1',
    messagingSenderId: '965932386436',
    projectId: 'loanapp-41407',
  );

 /* static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI_X6rHfryRWWHvcI8F0CPRzPOCgRExjk',
    appId: '1:141691262710:ios:dc7c8e8580bcb2c25f3ed7',
    messagingSenderId: '141691262710',
    projectId: 'cunsumerb2cdebug',
    iosBundleId: 'com.sk.zila',
  );*/

 /* static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDooSUGSf63Ghq02_iIhtnmwMDs4HlWS6c',
    appId: '1:406099696497:ios:0e034b18ffc943ec3574d0',
    messagingSenderId: '406099696497',
    projectId: 'flutterfire-e2e-tests',
    databaseURL:
    'https://flutterfire-e2e-tests-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfire-e2e-tests.appspot.com',
    androidClientId:
    '406099696497-17qn06u8a0dc717u8ul7s49ampk13lul.apps.googleusercontent.com',
    iosClientId:
    '406099696497-36nc77dcqom262b6dehoanhsqdnkq27j.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.remoteconfig.example',
  );*/
}